package com.learnjava.todo.service.impl;

import com.learnjava.todo.dto.request.CreateTodoRequest;
import com.learnjava.todo.dto.request.TodoFilterRequest;
import com.learnjava.todo.dto.request.UpdateTodoRequest;
import com.learnjava.todo.dto.response.PagedResponse;
import com.learnjava.todo.dto.response.TodoResponse;
import com.learnjava.todo.model.Todo;
import com.learnjava.todo.repository.TodoRepository;
import com.learnjava.todo.service.TodoMapper;
import com.learnjava.todo.service.TodoService;
import com.learnjava.todo.service.TodoSpecification;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;

@Slf4j
@Service
@Transactional
// @RequiredArgsConstructor replaces our manual constructor.
// Lombok generates a constructor with all final fields — Spring uses it for injection.
// This is cleaner than writing a constructor manually, especially as we add dependencies.
@RequiredArgsConstructor
public class TodoServiceImpl implements TodoService {

    private final TodoRepository todoRepository;

    // TodoMapper is now a Spring-managed bean (@Component), generated by MapStruct.
    // We inject it via constructor (via @RequiredArgsConstructor) — same as any other bean.
    // Previously we called TodoMapper.staticMethod() — now it's todoMapper.instanceMethod().
    private final TodoMapper todoMapper;

    @Override
    @Transactional(readOnly = true)
    public PagedResponse<TodoResponse> getTodos(TodoFilterRequest filter, Pageable pageable) {
        log.debug("Fetching todos — filter: {}, page: {}, size: {}",
                filter, pageable.getPageNumber(), pageable.getPageSize());

        Specification<Todo> spec = TodoSpecification.fromFilter(filter);
        Page<Todo> page = todoRepository.findAll(spec, pageable);

        // toPagedResponse lives here in the service — it wraps pagination metadata,
        // which is service-level orchestration, not entity-to-DTO field mapping.
        // MapStruct handles field mapping; the service handles structural wrapping.
        return PagedResponse.<TodoResponse>builder()
                .content(page.getContent().stream().map(todoMapper::toResponse).toList())
                .page(page.getNumber())
                .size(page.getSize())
                .totalElements(page.getTotalElements())
                .totalPages(page.getTotalPages())
                .last(page.isLast())
                .build();
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<TodoResponse> getTodoById(Long id) {
        log.debug("Looking up todo with id: {}", id);
        return todoRepository.findById(id)
                .map(todoMapper::toResponse);
    }

    @Override
    public TodoResponse createTodo(CreateTodoRequest request) {
        log.debug("Creating todo with title: {}", request.getTitle());
        // todoMapper.toModel() is MapStruct-generated — same logic as before,
        // but now auto-generated from the @Mapping annotations on the interface.
        Todo todo = todoMapper.toModel(request);
        Todo saved = todoRepository.save(todo);
        log.debug("Created todo with id: {}", saved.getId());
        return todoMapper.toResponse(saved);
    }

    @Override
    public Optional<TodoResponse> updateTodo(Long id, UpdateTodoRequest request) {
        log.debug("Attempting to update todo with id: {}", id);

        // IMPROVED PATTERN with @MappingTarget:
        // 1. Load the existing entity from DB (or return empty if not found)
        // 2. Apply the request fields ON TOP of the existing entity — in place
        // 3. Save — Hibernate sees the dirty fields and issues a minimal UPDATE
        //
        // This is better than the old approach (creating a new Todo with the id)
        // because it preserves any fields NOT in UpdateTodoRequest (e.g., createdAt
        // in Phase 12, or any future fields we don't want overwritten on update).
        return todoRepository.findById(id)
                .map(existingTodo -> {
                    todoMapper.updateModel(existingTodo, request); // mutates existingTodo
                    Todo saved = todoRepository.save(existingTodo);
                    return todoMapper.toResponse(saved);
                });
    }

    @Override
    public boolean deleteTodo(Long id) {
        log.debug("Attempting to delete todo with id: {}", id);
        if (!todoRepository.existsById(id)) {
            return false;
        }
        todoRepository.deleteById(id);
        return true;
    }
}
