package com.learnjava.todo.service.impl;

import com.learnjava.todo.config.CacheConfig;
import com.learnjava.todo.dto.request.CreateTodoRequest;
import com.learnjava.todo.dto.request.TodoFilterRequest;
import com.learnjava.todo.dto.request.UpdateTodoRequest;
import com.learnjava.todo.dto.response.PagedResponse;
import com.learnjava.todo.dto.response.TodoResponse;
import com.learnjava.todo.model.Todo;
import com.learnjava.todo.repository.TodoRepository;
import com.learnjava.todo.service.TodoMapper;
import com.learnjava.todo.service.TodoService;
import com.learnjava.todo.service.TodoSpecification;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;

@Slf4j
@Service
@Transactional
// @RequiredArgsConstructor replaces our manual constructor.
// Lombok generates a constructor with all final fields — Spring uses it for injection.
// This is cleaner than writing a constructor manually, especially as we add dependencies.
@RequiredArgsConstructor
public class TodoServiceImpl implements TodoService {

    private final TodoRepository todoRepository;

    // TodoMapper is now a Spring-managed bean (@Component), generated by MapStruct.
    // We inject it via constructor (via @RequiredArgsConstructor) — same as any other bean.
    // Previously we called TodoMapper.staticMethod() — now it's todoMapper.instanceMethod().
    private final TodoMapper todoMapper;

    @Override
    @Transactional(readOnly = true)
    public PagedResponse<TodoResponse> getTodos(TodoFilterRequest filter, Pageable pageable) {
        log.debug("Fetching todos — filter: {}, page: {}, size: {}",
                filter, pageable.getPageNumber(), pageable.getPageSize());

        Specification<Todo> spec = TodoSpecification.fromFilter(filter);
        Page<Todo> page = todoRepository.findAll(spec, pageable);

        // toPagedResponse lives here in the service — it wraps pagination metadata,
        // which is service-level orchestration, not entity-to-DTO field mapping.
        // MapStruct handles field mapping; the service handles structural wrapping.
        return PagedResponse.<TodoResponse>builder()
                .content(page.getContent().stream().map(todoMapper::toResponse).toList())
                .page(page.getNumber())
                .size(page.getSize())
                .totalElements(page.getTotalElements())
                .totalPages(page.getTotalPages())
                .last(page.isLast())
                .build();
    }

    // @Cacheable: before this method runs, Spring checks the "todos" cache for a key = id.
    //   Cache HIT  → return the cached TodoResponse immediately (DB never called).
    //   Cache MISS → call the method, store the returned Optional in the cache, return it.
    //
    // The cache key is the method parameter 'id' by default.
    // Spring caches the full return value — including Optional.empty() for not-found ids.
    // This prevents repeated DB lookups for ids that don't exist.
    @Override
    @Cacheable(value = CacheConfig.TODOS_CACHE, key = "#id")
    @Transactional(readOnly = true)
    public Optional<TodoResponse> getTodoById(Long id) {
        log.debug("Cache MISS — loading todo {} from database", id);
        return todoRepository.findById(id)
                .map(todoMapper::toResponse);
    }

    // No cache annotation here — createTodo assigns a new ID that was never in the cache.
    // There is no existing entry to evict and no reason to pre-populate the cache on create.
    @Override
    public TodoResponse createTodo(CreateTodoRequest request) {
        log.debug("Creating todo with title: {}", request.getTitle());
        Todo todo = todoMapper.toModel(request);
        Todo saved = todoRepository.save(todo);
        log.debug("Created todo with id: {}", saved.getId());
        return todoMapper.toResponse(saved);
    }

    // @CacheEvict: after this method completes, remove the entry for 'id' from "todos" cache.
    // WHY evict on update? The cached TodoResponse for this id is now stale — it holds
    // the OLD data. The next getTodoById(id) call must miss the cache and reload from DB.
    //
    // key = "#id" — SpEL expression that resolves to the method's 'id' parameter.
    // beforeInvocation = false (default) — evict AFTER the method succeeds.
    //   If the update throws an exception, the cache entry is preserved (still valid).
    @Override
    @CacheEvict(value = CacheConfig.TODOS_CACHE, key = "#id")
    public Optional<TodoResponse> updateTodo(Long id, UpdateTodoRequest request) {
        log.debug("Updating todo {} — evicting from cache", id);
        return todoRepository.findById(id)
                .map(existingTodo -> {
                    todoMapper.updateModel(existingTodo, request);
                    Todo saved = todoRepository.save(existingTodo);
                    return todoMapper.toResponse(saved);
                });
    }

    // @CacheEvict: after deletion, remove the entry for this id.
    // If not evicted, future getTodoById(id) calls would return the deleted todo from cache.
    @Override
    @CacheEvict(value = CacheConfig.TODOS_CACHE, key = "#id")
    public boolean deleteTodo(Long id) {
        log.debug("Deleting todo {} — evicting from cache", id);
        if (!todoRepository.existsById(id)) {
            return false;
        }
        todoRepository.deleteById(id);
        return true;
    }
}
