-- V1: Create the todos table.
-- This is the initial schema — run once on a fresh database.
-- Column types are chosen to be valid on both H2 (MODE=PostgreSQL) and real PostgreSQL.
--
-- Why BIGSERIAL on PostgreSQL but BIGINT GENERATED BY DEFAULT AS IDENTITY on standard SQL?
-- We use 'id BIGINT GENERATED BY DEFAULT AS IDENTITY' — ANSI SQL 2003 standard syntax.
-- H2 in PostgreSQL mode supports it. PostgreSQL 10+ supports it. Safe for both.
--
-- Why TEXT for title/description?
-- TEXT has no length limit in PostgreSQL. VARCHAR(255) is an arbitrary cap.
-- Since we validate length in Java (@Size), the DB column type can be TEXT.

CREATE TABLE IF NOT EXISTS todos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT        NOT NULL,
    description TEXT,
    completed   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL
);
