-- V2: Create the users table.
-- Added as a separate migration from V1 because users were introduced in Phase 10
-- (after todos). In real projects, each feature's schema change is its own version.
--
-- Why TEXT for password?
-- BCrypt hashes are always 60 characters. Using TEXT avoids any accidental truncation
-- if you ever switch algorithms (Argon2 hashes can be longer).
--
-- Why 'username' as UNIQUE NOT NULL?
-- Username is the login identifier — must be unique across all users.
-- NOT NULL enforced at DB level as a safety net (Java validation is the first line).

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT        NOT NULL UNIQUE,
    password    TEXT        NOT NULL,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL
);
